### ISSUE TITLE
Structured parameter implementation

### ISSUE THREAD

**Issue by asm582** [kubernetes-sigs/dra-example-driver#44]
Can we please share pointers if we have implemented structured parameters for example DRA driver, thanks

**Comment by klueska** [comment]
I started looking into it, but haven't finished it. We plan to release something here to coincide with the k8s 1.30 image provided by `kind`.

**Comment by klueska** [comment]
I now have updates to this repo for structured parameters staged here:
https://github.com/kubernetes-sigs/dra-example-driver/tree/structured-parameters
