### ISSUE TITLE
update for Kubernetes 1.32

### ISSUE THREAD

**Issue by pohly** [kubernetes-sigs/dra-example-driver#67]
- Go dependencies have to be updated.
- Replace v1alpha3 with v1beta1 *or* add it (`templates/validatingadmissionpolicy.yaml`).

**Comment by trainyao** [comment]
maybe we should replace all `v1alpha3` to `v1beta1`? 

I just pull up a v1.32.0-rc0 cluster, and find out kube-scheduler and kube-controller-manager can not be Ready if kube-apiserver start with flag `--runtime-config=resource.k8s.io/v1alpha3`.
I think alpha3 is about to be deprecated.

**Comment by klueska** [comment]
Yes, I plan to do it next week on a branch when I am back in the office.
But we won’t merge it until after the 1.32 release actually goes out and is
available in kind.

~Kevin


trainyao ***@***.***> schrieb am Fr. 29. Nov. 2024 um 20:24:
